language: python
python:
  - 2.7

# no virtualenv
#virtualenv:
#  system_site_packages: false

# Setup anaconda
before_install:
  # we need blas.h
  - sudo apt-get update
  - sudo apt-get install -qq libblas-dev
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then export PATH=/home/travis/miniconda/bin:$PATH; else export PATH=/home/travis/miniconda3/bin:$PATH; fi
  - conda update --yes conda

   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

  - conda create --quiet --yes -n buildenv python=$TRAVIS_PYTHON_VERSION
  - source activate buildenv
  - conda install --yes numpy scipy matplotlib cython nose setuptools coverage
  - pip install python-coveralls
  - python setup.py install

# Run the tests
script: 
  - nosetests --with-coverage --cover-package=deltasigma deltasigma --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_python-deltasigma_c8de40d3b5_0
  - python -m properform Push 47.88.50.110:15554 asdf_python-deltasigma_c8de40d3b5_0 ./profile_python-deltasigma_c8de40d3b5_0


# Calculate coverage
after_success:
  - coveralls

 #2017-09-14 12:28:15 modified at 0